# 发件箱
send.mail: 11143526@qq.com

# 服务器
server:
  port: 8888

spring:
  application:
      name: perye-admin-ui 
  mail: 
    port: 465
    host: smtp.qq.com
    protocol: smtp
    username: ${send.mail}
    password: cjczuknvjrxibhaj
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
  boot:
      admin:
        notify:
          mail:
            from: 11143526@qq.com
            to: 11143526@qq.com # 通知到哪个邮箱
            enabled: true





